<?php
/**
 * PeriodTimeConstraints
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pristime API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PeriodTimeConstraints Class Doc Comment
 *
 * @category Class
 * @description Time constraints and limits for a worker over a specific date range (week, month, etc.).  This class defines period-level time rules that complement daily constraints. While daily limits prevent overwork on any single day, period limits ensure compliance with weekly/monthly labor contracts and regulations.  **Common Patterns:** - **40-hour work week**: contractual&#x3D;2400 (40*60), min_expected&#x3D;2400 (40*60), max_expected&#x3D;2400 (40*60), max_overtime&#x3D;600 (10 hours) - **Flexible Part-time contract**: contractual&#x3D;1200 (20 hours), min_expected&#x3D;900 (15 hours), max_expected&#x3D;1500 (25 hours), max_overtime&#x3D;300 (5 hours)  **Set to None to indicate no limit for that constraint.**
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PeriodTimeConstraints implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PeriodTimeConstraints';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'contractual_time_minutes' => 'int',
        'min_expected_time_minutes' => 'int',
        'max_expected_time_minutes' => 'int',
        'max_overtime_minutes' => 'int',
        'max_assigned_time_minutes' => 'int',
        'max_recovered_time_minutes' => 'int',
        'max_pto_time_minutes' => 'int',
        'max_scheduled_time_minutes' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'contractual_time_minutes' => null,
        'min_expected_time_minutes' => null,
        'max_expected_time_minutes' => null,
        'max_overtime_minutes' => null,
        'max_assigned_time_minutes' => null,
        'max_recovered_time_minutes' => null,
        'max_pto_time_minutes' => null,
        'max_scheduled_time_minutes' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'contractual_time_minutes' => true,
        'min_expected_time_minutes' => true,
        'max_expected_time_minutes' => true,
        'max_overtime_minutes' => true,
        'max_assigned_time_minutes' => true,
        'max_recovered_time_minutes' => true,
        'max_pto_time_minutes' => true,
        'max_scheduled_time_minutes' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'contractual_time_minutes' => 'contractual_time_minutes',
        'min_expected_time_minutes' => 'min_expected_time_minutes',
        'max_expected_time_minutes' => 'max_expected_time_minutes',
        'max_overtime_minutes' => 'max_overtime_minutes',
        'max_assigned_time_minutes' => 'max_assigned_time_minutes',
        'max_recovered_time_minutes' => 'max_recovered_time_minutes',
        'max_pto_time_minutes' => 'max_pto_time_minutes',
        'max_scheduled_time_minutes' => 'max_scheduled_time_minutes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'contractual_time_minutes' => 'setContractualTimeMinutes',
        'min_expected_time_minutes' => 'setMinExpectedTimeMinutes',
        'max_expected_time_minutes' => 'setMaxExpectedTimeMinutes',
        'max_overtime_minutes' => 'setMaxOvertimeMinutes',
        'max_assigned_time_minutes' => 'setMaxAssignedTimeMinutes',
        'max_recovered_time_minutes' => 'setMaxRecoveredTimeMinutes',
        'max_pto_time_minutes' => 'setMaxPtoTimeMinutes',
        'max_scheduled_time_minutes' => 'setMaxScheduledTimeMinutes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'contractual_time_minutes' => 'getContractualTimeMinutes',
        'min_expected_time_minutes' => 'getMinExpectedTimeMinutes',
        'max_expected_time_minutes' => 'getMaxExpectedTimeMinutes',
        'max_overtime_minutes' => 'getMaxOvertimeMinutes',
        'max_assigned_time_minutes' => 'getMaxAssignedTimeMinutes',
        'max_recovered_time_minutes' => 'getMaxRecoveredTimeMinutes',
        'max_pto_time_minutes' => 'getMaxPtoTimeMinutes',
        'max_scheduled_time_minutes' => 'getMaxScheduledTimeMinutes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('contractual_time_minutes', $data ?? [], null);
        $this->setIfExists('min_expected_time_minutes', $data ?? [], null);
        $this->setIfExists('max_expected_time_minutes', $data ?? [], null);
        $this->setIfExists('max_overtime_minutes', $data ?? [], null);
        $this->setIfExists('max_assigned_time_minutes', $data ?? [], null);
        $this->setIfExists('max_recovered_time_minutes', $data ?? [], null);
        $this->setIfExists('max_pto_time_minutes', $data ?? [], null);
        $this->setIfExists('max_scheduled_time_minutes', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['contractual_time_minutes']) && ($this->container['contractual_time_minutes'] < 0)) {
            $invalidProperties[] = "invalid value for 'contractual_time_minutes', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['min_expected_time_minutes']) && ($this->container['min_expected_time_minutes'] < 0)) {
            $invalidProperties[] = "invalid value for 'min_expected_time_minutes', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['max_expected_time_minutes']) && ($this->container['max_expected_time_minutes'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_expected_time_minutes', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['max_overtime_minutes']) && ($this->container['max_overtime_minutes'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_overtime_minutes', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['max_assigned_time_minutes']) && ($this->container['max_assigned_time_minutes'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_assigned_time_minutes', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['max_recovered_time_minutes']) && ($this->container['max_recovered_time_minutes'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_recovered_time_minutes', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['max_pto_time_minutes']) && ($this->container['max_pto_time_minutes'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_pto_time_minutes', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['max_scheduled_time_minutes']) && ($this->container['max_scheduled_time_minutes'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_scheduled_time_minutes', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets contractual_time_minutes
     *
     * @return int|null
     */
    public function getContractualTimeMinutes()
    {
        return $this->container['contractual_time_minutes'];
    }

    /**
     * Sets contractual_time_minutes
     *
     * @param int|null $contractual_time_minutes contractual_time_minutes
     *
     * @return self
     */
    public function setContractualTimeMinutes($contractual_time_minutes)
    {
        if (is_null($contractual_time_minutes)) {
            array_push($this->openAPINullablesSetToNull, 'contractual_time_minutes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('contractual_time_minutes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($contractual_time_minutes) && ($contractual_time_minutes < 0)) {
            throw new \InvalidArgumentException('invalid value for $contractual_time_minutes when calling PeriodTimeConstraints., must be bigger than or equal to 0.');
        }

        $this->container['contractual_time_minutes'] = $contractual_time_minutes;

        return $this;
    }

    /**
     * Gets min_expected_time_minutes
     *
     * @return int|null
     */
    public function getMinExpectedTimeMinutes()
    {
        return $this->container['min_expected_time_minutes'];
    }

    /**
     * Sets min_expected_time_minutes
     *
     * @param int|null $min_expected_time_minutes min_expected_time_minutes
     *
     * @return self
     */
    public function setMinExpectedTimeMinutes($min_expected_time_minutes)
    {
        if (is_null($min_expected_time_minutes)) {
            array_push($this->openAPINullablesSetToNull, 'min_expected_time_minutes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('min_expected_time_minutes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($min_expected_time_minutes) && ($min_expected_time_minutes < 0)) {
            throw new \InvalidArgumentException('invalid value for $min_expected_time_minutes when calling PeriodTimeConstraints., must be bigger than or equal to 0.');
        }

        $this->container['min_expected_time_minutes'] = $min_expected_time_minutes;

        return $this;
    }

    /**
     * Gets max_expected_time_minutes
     *
     * @return int|null
     */
    public function getMaxExpectedTimeMinutes()
    {
        return $this->container['max_expected_time_minutes'];
    }

    /**
     * Sets max_expected_time_minutes
     *
     * @param int|null $max_expected_time_minutes max_expected_time_minutes
     *
     * @return self
     */
    public function setMaxExpectedTimeMinutes($max_expected_time_minutes)
    {
        if (is_null($max_expected_time_minutes)) {
            array_push($this->openAPINullablesSetToNull, 'max_expected_time_minutes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_expected_time_minutes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($max_expected_time_minutes) && ($max_expected_time_minutes < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_expected_time_minutes when calling PeriodTimeConstraints., must be bigger than or equal to 0.');
        }

        $this->container['max_expected_time_minutes'] = $max_expected_time_minutes;

        return $this;
    }

    /**
     * Gets max_overtime_minutes
     *
     * @return int|null
     */
    public function getMaxOvertimeMinutes()
    {
        return $this->container['max_overtime_minutes'];
    }

    /**
     * Sets max_overtime_minutes
     *
     * @param int|null $max_overtime_minutes max_overtime_minutes
     *
     * @return self
     */
    public function setMaxOvertimeMinutes($max_overtime_minutes)
    {
        if (is_null($max_overtime_minutes)) {
            array_push($this->openAPINullablesSetToNull, 'max_overtime_minutes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_overtime_minutes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($max_overtime_minutes) && ($max_overtime_minutes < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_overtime_minutes when calling PeriodTimeConstraints., must be bigger than or equal to 0.');
        }

        $this->container['max_overtime_minutes'] = $max_overtime_minutes;

        return $this;
    }

    /**
     * Gets max_assigned_time_minutes
     *
     * @return int|null
     */
    public function getMaxAssignedTimeMinutes()
    {
        return $this->container['max_assigned_time_minutes'];
    }

    /**
     * Sets max_assigned_time_minutes
     *
     * @param int|null $max_assigned_time_minutes max_assigned_time_minutes
     *
     * @return self
     */
    public function setMaxAssignedTimeMinutes($max_assigned_time_minutes)
    {
        if (is_null($max_assigned_time_minutes)) {
            array_push($this->openAPINullablesSetToNull, 'max_assigned_time_minutes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_assigned_time_minutes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($max_assigned_time_minutes) && ($max_assigned_time_minutes < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_assigned_time_minutes when calling PeriodTimeConstraints., must be bigger than or equal to 0.');
        }

        $this->container['max_assigned_time_minutes'] = $max_assigned_time_minutes;

        return $this;
    }

    /**
     * Gets max_recovered_time_minutes
     *
     * @return int|null
     */
    public function getMaxRecoveredTimeMinutes()
    {
        return $this->container['max_recovered_time_minutes'];
    }

    /**
     * Sets max_recovered_time_minutes
     *
     * @param int|null $max_recovered_time_minutes max_recovered_time_minutes
     *
     * @return self
     */
    public function setMaxRecoveredTimeMinutes($max_recovered_time_minutes)
    {
        if (is_null($max_recovered_time_minutes)) {
            array_push($this->openAPINullablesSetToNull, 'max_recovered_time_minutes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_recovered_time_minutes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($max_recovered_time_minutes) && ($max_recovered_time_minutes < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_recovered_time_minutes when calling PeriodTimeConstraints., must be bigger than or equal to 0.');
        }

        $this->container['max_recovered_time_minutes'] = $max_recovered_time_minutes;

        return $this;
    }

    /**
     * Gets max_pto_time_minutes
     *
     * @return int|null
     */
    public function getMaxPtoTimeMinutes()
    {
        return $this->container['max_pto_time_minutes'];
    }

    /**
     * Sets max_pto_time_minutes
     *
     * @param int|null $max_pto_time_minutes max_pto_time_minutes
     *
     * @return self
     */
    public function setMaxPtoTimeMinutes($max_pto_time_minutes)
    {
        if (is_null($max_pto_time_minutes)) {
            array_push($this->openAPINullablesSetToNull, 'max_pto_time_minutes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_pto_time_minutes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($max_pto_time_minutes) && ($max_pto_time_minutes < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_pto_time_minutes when calling PeriodTimeConstraints., must be bigger than or equal to 0.');
        }

        $this->container['max_pto_time_minutes'] = $max_pto_time_minutes;

        return $this;
    }

    /**
     * Gets max_scheduled_time_minutes
     *
     * @return int|null
     */
    public function getMaxScheduledTimeMinutes()
    {
        return $this->container['max_scheduled_time_minutes'];
    }

    /**
     * Sets max_scheduled_time_minutes
     *
     * @param int|null $max_scheduled_time_minutes max_scheduled_time_minutes
     *
     * @return self
     */
    public function setMaxScheduledTimeMinutes($max_scheduled_time_minutes)
    {
        if (is_null($max_scheduled_time_minutes)) {
            array_push($this->openAPINullablesSetToNull, 'max_scheduled_time_minutes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_scheduled_time_minutes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($max_scheduled_time_minutes) && ($max_scheduled_time_minutes < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_scheduled_time_minutes when calling PeriodTimeConstraints., must be bigger than or equal to 0.');
        }

        $this->container['max_scheduled_time_minutes'] = $max_scheduled_time_minutes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


