<?php
/**
 * ProvidedShiftsDurations
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pristime Workforce Scheduling API
 *
 * ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules using Mixed Integer Programming (MIP).          ## Authentication          All endpoints require an API key in the `Pristime-API-Key` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: antoine.hachez@pristime.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ProvidedShiftsDurations Class Doc Comment
 *
 * @category Class
 * @description These metrics help you understand how much of your schedule was modified during optimization and the nature of those changes. All values are in minutes.  **Assignment Change Patterns:**  **Stability Metrics:** - kept_assignment: Shifts that kept their original worker assignments - remained_unassigned: Shifts that stayed unassigned (no available workers)  **Change Metrics:** - changed_assignment: Assigned shifts that got different workers - lost_assignment: Previously assigned shifts that became unassigned - gained_assignment: Unassigned shifts that got workers
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProvidedShiftsDurations implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProvidedShiftsDurations';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'kept_assignment_minutes' => 'int',
        'changed_assignment_minutes' => 'int',
        'lost_assignment_minutes' => 'int',
        'remained_unassigned_minutes' => 'int',
        'gained_assignment_minutes' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'kept_assignment_minutes' => null,
        'changed_assignment_minutes' => null,
        'lost_assignment_minutes' => null,
        'remained_unassigned_minutes' => null,
        'gained_assignment_minutes' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'kept_assignment_minutes' => false,
        'changed_assignment_minutes' => false,
        'lost_assignment_minutes' => false,
        'remained_unassigned_minutes' => false,
        'gained_assignment_minutes' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kept_assignment_minutes' => 'kept_assignment_minutes',
        'changed_assignment_minutes' => 'changed_assignment_minutes',
        'lost_assignment_minutes' => 'lost_assignment_minutes',
        'remained_unassigned_minutes' => 'remained_unassigned_minutes',
        'gained_assignment_minutes' => 'gained_assignment_minutes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kept_assignment_minutes' => 'setKeptAssignmentMinutes',
        'changed_assignment_minutes' => 'setChangedAssignmentMinutes',
        'lost_assignment_minutes' => 'setLostAssignmentMinutes',
        'remained_unassigned_minutes' => 'setRemainedUnassignedMinutes',
        'gained_assignment_minutes' => 'setGainedAssignmentMinutes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kept_assignment_minutes' => 'getKeptAssignmentMinutes',
        'changed_assignment_minutes' => 'getChangedAssignmentMinutes',
        'lost_assignment_minutes' => 'getLostAssignmentMinutes',
        'remained_unassigned_minutes' => 'getRemainedUnassignedMinutes',
        'gained_assignment_minutes' => 'getGainedAssignmentMinutes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('kept_assignment_minutes', $data ?? [], null);
        $this->setIfExists('changed_assignment_minutes', $data ?? [], null);
        $this->setIfExists('lost_assignment_minutes', $data ?? [], null);
        $this->setIfExists('remained_unassigned_minutes', $data ?? [], null);
        $this->setIfExists('gained_assignment_minutes', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['kept_assignment_minutes'] === null) {
            $invalidProperties[] = "'kept_assignment_minutes' can't be null";
        }
        if ($this->container['changed_assignment_minutes'] === null) {
            $invalidProperties[] = "'changed_assignment_minutes' can't be null";
        }
        if ($this->container['lost_assignment_minutes'] === null) {
            $invalidProperties[] = "'lost_assignment_minutes' can't be null";
        }
        if ($this->container['remained_unassigned_minutes'] === null) {
            $invalidProperties[] = "'remained_unassigned_minutes' can't be null";
        }
        if ($this->container['gained_assignment_minutes'] === null) {
            $invalidProperties[] = "'gained_assignment_minutes' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kept_assignment_minutes
     *
     * @return int
     */
    public function getKeptAssignmentMinutes()
    {
        return $this->container['kept_assignment_minutes'];
    }

    /**
     * Sets kept_assignment_minutes
     *
     * @param int $kept_assignment_minutes Total minutes of shifts that kept their original worker assignment. High values indicate scheduling stability with minimal disruption.
     *
     * @return self
     */
    public function setKeptAssignmentMinutes($kept_assignment_minutes)
    {
        if (is_null($kept_assignment_minutes)) {
            throw new \InvalidArgumentException('non-nullable kept_assignment_minutes cannot be null');
        }
        $this->container['kept_assignment_minutes'] = $kept_assignment_minutes;

        return $this;
    }

    /**
     * Gets changed_assignment_minutes
     *
     * @return int
     */
    public function getChangedAssignmentMinutes()
    {
        return $this->container['changed_assignment_minutes'];
    }

    /**
     * Sets changed_assignment_minutes
     *
     * @param int $changed_assignment_minutes Total minutes of shifts that were reassigned to different workers.
     *
     * @return self
     */
    public function setChangedAssignmentMinutes($changed_assignment_minutes)
    {
        if (is_null($changed_assignment_minutes)) {
            throw new \InvalidArgumentException('non-nullable changed_assignment_minutes cannot be null');
        }
        $this->container['changed_assignment_minutes'] = $changed_assignment_minutes;

        return $this;
    }

    /**
     * Gets lost_assignment_minutes
     *
     * @return int
     */
    public function getLostAssignmentMinutes()
    {
        return $this->container['lost_assignment_minutes'];
    }

    /**
     * Sets lost_assignment_minutes
     *
     * @param int $lost_assignment_minutes Total minutes of previously assigned shifts that became unassigned.
     *
     * @return self
     */
    public function setLostAssignmentMinutes($lost_assignment_minutes)
    {
        if (is_null($lost_assignment_minutes)) {
            throw new \InvalidArgumentException('non-nullable lost_assignment_minutes cannot be null');
        }
        $this->container['lost_assignment_minutes'] = $lost_assignment_minutes;

        return $this;
    }

    /**
     * Gets remained_unassigned_minutes
     *
     * @return int
     */
    public function getRemainedUnassignedMinutes()
    {
        return $this->container['remained_unassigned_minutes'];
    }

    /**
     * Sets remained_unassigned_minutes
     *
     * @param int $remained_unassigned_minutes Total minutes of shifts that stayed unassigned.
     *
     * @return self
     */
    public function setRemainedUnassignedMinutes($remained_unassigned_minutes)
    {
        if (is_null($remained_unassigned_minutes)) {
            throw new \InvalidArgumentException('non-nullable remained_unassigned_minutes cannot be null');
        }
        $this->container['remained_unassigned_minutes'] = $remained_unassigned_minutes;

        return $this;
    }

    /**
     * Gets gained_assignment_minutes
     *
     * @return int
     */
    public function getGainedAssignmentMinutes()
    {
        return $this->container['gained_assignment_minutes'];
    }

    /**
     * Sets gained_assignment_minutes
     *
     * @param int $gained_assignment_minutes Total minutes of previously unassigned shifts that gained workers.
     *
     * @return self
     */
    public function setGainedAssignmentMinutes($gained_assignment_minutes)
    {
        if (is_null($gained_assignment_minutes)) {
            throw new \InvalidArgumentException('non-nullable gained_assignment_minutes cannot be null');
        }
        $this->container['gained_assignment_minutes'] = $gained_assignment_minutes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


