<?php
/**
 * AvailabilityTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pristime API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AvailabilityTest Class Doc Comment
 *
 * @category    Class
 * @description Defines a worker&#39;s availability preferences and restrictions for scheduling.  Availability is used by the optimizer to respect worker preferences and constraints: - **Unavailable periods**: Hard constraints - worker cannot be assigned shifts during these times - **Preferred periods**: Soft preferences - optimizer tries to assign shifts during these times - **Unpreferred periods**: Soft constraints - optimizer avoids these times but can use them if needed  All periods use standard timing: start time included, end time excluded, whole minutes only.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AvailabilityTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Availability"
     */
    public function testAvailability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unavailable_periods"
     */
    public function testPropertyUnavailablePeriods()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "preferred_periods"
     */
    public function testPropertyPreferredPeriods()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unpreferred_periods"
     */
    public function testPropertyUnpreferredPeriods()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
