<?php
/**
 * PeriodDayConstraintsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PristimeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pristime Workforce Scheduling API
 *
 * ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Pristime-API-Key` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: antoine.hachez@pristime.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PristimeSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PeriodDayConstraintsTest Class Doc Comment
 *
 * @category    Class
 * @description Limits on the number of working days within a date range period. After a worker has reached the max_expected_days, any additional days will be scheduled as overtime.  **Common Patterns:** - **5-day work week**: scheduled_max&#x3D;5 (Monday-Friday only) - **Part-time**: expected_max&#x3D;3, scheduled_max&#x3D;4 (3 guaranteed, up to 4 total)
 * @package     PristimeSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PeriodDayConstraintsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PeriodDayConstraints"
     */
    public function testPeriodDayConstraints()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "max_expected_days"
     */
    public function testPropertyMaxExpectedDays()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "max_scheduled_days"
     */
    public function testPropertyMaxScheduledDays()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
