<?php
/**
 * ProvidedShiftsDurationsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pristime Workforce Scheduling API
 *
 * ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules using Mixed Integer Programming (MIP).          ## Authentication          All endpoints require an API key in the `Pristime-API-Key` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: antoine.hachez@pristime.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProvidedShiftsDurationsTest Class Doc Comment
 *
 * @category    Class
 * @description These metrics help you understand how much of your schedule was modified during optimization and the nature of those changes. All values are in minutes.  **Assignment Change Patterns:**  **Stability Metrics:** - kept_assignment: Shifts that kept their original worker assignments - remained_unassigned: Shifts that stayed unassigned (no available workers)  **Change Metrics:** - changed_assignment: Assigned shifts that got different workers - lost_assignment: Previously assigned shifts that became unassigned - gained_assignment: Unassigned shifts that got workers
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProvidedShiftsDurationsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProvidedShiftsDurations"
     */
    public function testProvidedShiftsDurations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "kept_assignment_minutes"
     */
    public function testPropertyKeptAssignmentMinutes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "changed_assignment_minutes"
     */
    public function testPropertyChangedAssignmentMinutes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lost_assignment_minutes"
     */
    public function testPropertyLostAssignmentMinutes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "remained_unassigned_minutes"
     */
    public function testPropertyRemainedUnassignedMinutes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gained_assignment_minutes"
     */
    public function testPropertyGainedAssignmentMinutes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
