<?php
/**
 * WorkerCostTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PristimePhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pristime Workforce Scheduling API
 *
 * ## Pristime Workforce Scheduling API          The Pristime Scheduling API lets clients provide workers, shifts,         and constraints, and returns optimized schedules.          ## Authentication          All endpoints require an API key in the `Pristime-API-Key` header.          ## Support          For technical support, contact us at antoine.hachez@pristime.com
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: antoine.hachez@pristime.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PristimePhpSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WorkerCostTest Class Doc Comment
 *
 * @category    Class
 * @description WorkerCost
 * @package     PristimePhpSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WorkerCostTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WorkerCost"
     */
    public function testWorkerCost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "per_hour_of_positive_flextime_balance"
     */
    public function testPropertyPerHourOfPositiveFlextimeBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "per_hour_of_positive_overtime_balance"
     */
    public function testPropertyPerHourOfPositiveOvertimeBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "per_hour_of_unpreferred_period"
     */
    public function testPropertyPerHourOfUnpreferredPeriod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
